services:
  movieboom.web:
    container_name: movieboom.web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      movieboom.database:
        condition: service_healthy
    
  movieboom.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: movieboom.database
    environment:
      - MSSQL_SA_PASSWORD=Password123
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    healthcheck:
      test: ["CMD-SHELL", "pgrep -x sqlservr"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  movieboom.email:
    image: axllent/mailpit:latest
    container_name: movieboom.mailpit
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025
