name: Integration Tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
      - name: Restore
        run: dotnet restore tests/Application.IntegrationTests/Application.IntegrationTests.csproj
      - name: Build
        run: dotnet build tests/Application.IntegrationTests/Application.IntegrationTests.csproj --no-restore

  integration-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
      - name: Run Integration Tests
        run: dotnet test tests/Application.IntegrationTests/Application.IntegrationTests.csproj --no-build
